### ISSUE TITLE
Update system not working

### ISSUE THREAD

**Issue by MoonLightBaka** [MonnXI/ZenShell#7]
**Describe the bug**
The update system is not working

**To Reproduce**
1. Launch ZenShell
2. Type update
3. Then choose the version
4. It's gonna give you an error

**Expected behavior**
This is supposed to download the latest version of ZenShell

**Desktop (please complete the following information):**
 - OS: Debian 12 bookworm x86_64
 - Version 1.2.2
 - Bash Version 5

**Comment by MonnXI** [comment]
I am going to be working on that really soon thank you for the information
